### ISSUE TITLE
Tricks to keep it from crashing node?

### ISSUE THREAD

**Issue by laduke** [yoshuawuyts/server-router#27]
Just out of curiosity

If you have like
```
  router.route('GET', '/api/*', fourofour)
  router.route('GET', '/api/bar', handle) 
  router.route('GET', '*', index)

  http.createServer(router.start())
    .listen(9000, function () {
      console.log(`http://localhost:${this.address().port}  ready`)
    })
```
/api/bar/x crashes

Do I just need to remember to add a catchall for every level of route?

`router.route('GET', '/api/bar/*', fourofour) `

```
exit Error: route 'GET/api/bar/x' did not match
    at match (/Users/travis/experiment/node_modules/wayfarer/index.js:69:11)
    at ServerRouter.emit [as _router] (/Users/travis/experiments/zt-spawn2/node_modules/wayfarer/index.js:49:19)
    at ServerRouter.match (/Users/travis/experiments/zt-spawn2/node_modules/server-router/index.js:40:15)
    at Server.<anonymous> (/Users/travis/experiments/zt-spawn2/node_modules/server-router/index.js:46:10)
    at Server.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:628:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
```

**Comment by perguth** [comment]
You could do

```js
router.route('get', '*', function (req, res, params) {
  res.end('Route not defined')
})
```

but then it would probably still crash when receiving POSTs. That's not good imho. 😞 

We should not crash on undefined routes!
